# Generated by Django 2.2.13 on 2021-02-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_river_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='my_state_field',
        ),
    ]
