# Generated by Django 2.2.13 on 2021-02-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_river_app', '0002_auto_20210223_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='my_state_field',
            new_name='status',
        ),
    ]
